- package.json
- pnpm-lock.yaml
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user …
> fixed nodejs version

- app/page.tsx
- package.json
- pnpm-lock.yaml
- styles/colors.ts
- styles/texts.ts
Review colors.ts, texts.ts.
https://styled-components.com/docs/basics
CC: @itsliterallymonique
> [GL] Make Global Style Sheets

- app/page.tsx
- components/ProjectModal/index.tsx
- components/ProjectModal/styles.ts
- package.json
- pnpm-lock.yaml
Imported react-modal to use for ProjectModal component and styled a little based off Figma. Also added ProjectModal component to home page, but will probably need to be moved.
https://github.com/user-attachments/assets/5d7993d1-58cd-46bb- …
> [PM] Make Project Modal Component

- api/supabase/queries/query.ts
- api/supabase/schema.ts
- app/page.tsx
- app/testing/page.tsx
- components/ProjectModal/index.tsx
- Added query function to fetch specfic project from database and used it in Project Modal component
- Updated schema variable names to match supabase (twas causing issues with not getting some of the variables if names were different) …
> [feat] Query Project Information from the Database to the Project Modal

- styles/colors.ts
Added `#` in front of the colors in `colors.ts`
CC: @itsliterallymonique
> [chore] Fixed colors.ts

- api/maps/AddMarkers.tsx
- api/maps/MarkerInfoWindow.tsx
- components/Map/map.tsx
- When you click on a marker, the map centers to the marker now
https://github.com/user-attachments/assets/05a6d1c6-af7e-45f1-a6cd-f4c26b7d476b
[//]: # "/[Required] Describe the order in which to review files and what to expect when …
> [feat] Center Project Marker when Project is Selected

- api/supabase/queries/query.ts
- components/ProjectModal/index.tsx
- components/ProjectModal/styles.ts
- next.config.mjs
- Created a query to fetch the default images that correspond to the renewable energy technology from supabase.
- Made the modal scrollable.
- Added alt description based on different images.
- Changed the project image in the modal to use next/image.
[//]: # "/[Required] Describe the order in which to review files and …
> [chore] Default Images & Scrollable Project Modal

- components/FilterBar/styles.ts
- components/KeyDevelopmentMilestone/index.tsx
- components/KeyDevelopmentMilestone/styles.ts
- components/ProjectModal/index.tsx
- components/SearchBar/styles.ts
- styles/colors.ts
- styles/texts.ts
Added new fonts
- **Fonts for tags:**`TagText2`
- **Filter heading fonts:** `FilterHeadingUnused` and `FilterHeadingInUse`
- **Filter Categories and Text Fonts:** `FilterCategoryText1`, `MinMaxTextUnused` and `MinMaxTextInUse`
- **Search Bar fonts:** `SearchBarTextUnused` and `SearchBarTextInUse`
- Changed IA Executed to IA Tendered as per POC request
- Changed **blue** to **electricBlue** for added specificity
- Changed MW / Mo to Megawatts (MW) for accuracy
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all …
> [fix] font fixes and wording adjustments

- assets/KDM-Icons/icons.tsx
- components/KDMDropdown/index.tsx
- components/ProjectsListingModal/index.tsx
- components/ProjectsListingModal/styles.ts
- added sort by button
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at …
> Style Closing Modal Button and Sort By Button

- components/Filter/index.tsx
- components/Filter/styles.ts
- components/FilterBar/index.tsx
- components/MapViewScreen/index.tsx
- components/ProjectSizeDropdown/index.tsx
- components/ProjectSizeDropdown/styles.ts
- types/schema.d.ts
- added Project Size dropdown for filtering
- created `ProjectSizeDropdown/index.tsx` and `ProjectSizeDropdown/styles.ts`
- modified other files in `components/Filter`, `components/FilterBar`, and `components/MapViewScreen` to include the new dropdown
[image placeholder]: <img src="place image link here!!!" width="240" …
> [style] added and styled Project Size dropdown

- assets/Project-Icons/icons.tsx
- components/Filter/styles.ts
- components/MapViewScreen/index.tsx
- components/ProjectsListingModal/index.tsx
- components/ProjectsListingModal/styles.ts
- added a button next to the projects modal that allows user to minimize the modal
- added search bar button to open the modal when clicked
- minor fix with sort by button style lol
UPDATE:
- moved search button and all filters (status, …
> [feat] Implement Closing All Projects Modal

- components/Filter/index.tsx
- components/FilterBar/index.tsx
- components/MapViewScreen/index.tsx
- components/ProjectSizeDropdown/index.tsx
- components/ProjectSizeHistogram/index.tsx
- components/ProjectSizeSlider/index.tsx
- components/ProjectSizeSlider/styles.css
- Project Size dropdown filters the projects on the map alongside the other dropdown filters
- adjusted some overall filtering logic in `/MapViewScreen` to allow for Project Size dropdown to work …
> [feat] Implement Project Size Filter Functionality

- components/ProjectsListingModal/index.tsx
- components/ProjectsListingModal/styles.ts
- styles/texts.ts
- Added the dropdown feature for the sort by button
- Added styling for the dropdown bar and components within the dropdown bar
- No functionality added atm
https://github.com/user-attachments/assets/eb9e2177-128b-43f8-8699-f84cb7a95eec …
> 126 Style Sort By Dropdown

- components/InfoModal/styles.ts
-converted info modal CSS to rem
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or …
> converted to rem

- assets/Dropdown-Icons/icons.tsx
- components/Filter/index.tsx
- components/FilterBar/index.tsx
- components/LocationCategory/styles.ts
- components/LocationCategoryPanel/index.tsx
- components/LocationDropdown/index.tsx
- components/LocationDropdown/styles.ts
- components/MapViewScreen/index.tsx
- components/ProjectSizeDropdown/index.tsx
- components/ProjectSizeDropdown/styles.ts
- components/ProjectSizeHistogram/index.tsx
- components/ProjectSizeSlider/index.tsx
- components/StatusDropdown/index.tsx
- components/TechnologyDropdown/index.tsx
- types/schema.d.ts
- allowed for all filters (but the project size filter itself + search) to dynamically change the histogram and average + min + max values in the project size filter
- ensured that the histogram slider stayed proportional to new histograms' min and max values
- fixed a bug where the filters were applying without clicking on the "Apply" button. We were previously incorrectly setting the selectedFilters with the entirety of tempFilters for each dropdown instead of just that dropdown's attribute
- replaced the "x"s with the up arrows for the filter dropdowns
- renamed variables + added comments in project size filter for much better readability
- fixed bug where app …
> [feat] [bug] [style] Created Dynamic + Styled Project Size Dropdown

- api/maps/AddMarkers.tsx
- api/maps/MarkerInfoWindow.tsx
- api/supabase/queries/query.ts
- components/MapViewScreen/index.tsx
- components/ProjectItem/index.tsx
- package.json
- pnpm-lock.yaml
- debugged and found 2 serious inefficiencies in our clustering logic (clustering upon loading & clustering upon filtering)
- prior implementation resulted in the app lagging with 200+ projects and crashing with 900+ projects...
- solution for clustering upon loading: instead of creating a new ReactDOM for every icon, we can set the innerHTML to a cached svg string in `/api/maps/AddMarkers`
- solution for clustering upon filtering:  instead of calling `addMarker` on each marker, we can add every marker into a list and then call `addMarkers`
- there was still additional lag when interacting with the map due to the high number of clusters...
- solution for the high …
> [feat] [bug] Optimized/Scaled Clustering & Enabled Marker Centering on Modal Click

- api/maps/AddMarkers.tsx
- api/maps/MarkerInfoWindow.tsx
- components/BottomBar/index.tsx
- components/Filter/index.tsx
- components/FilterBar/index.tsx
- components/MapViewScreen/index.tsx
- if a modal is opened (filter dropdown, legend modal, disclaimer modal, aggregation) and the user clicks into a project (either from the marker or on the left modal thing), all opened modals close.
- fixed bug where the marker info hover still shows if the user applies filters and the project disappears.
[image …
> Closing Modals + Marker Info Hover Bug

- api/supabase/queries/query.ts
- components/Filter/index.tsx
- components/FilterBar/index.tsx
- components/LocationCategoryPanel/index.tsx
- components/LocationDropdown/index.tsx
- components/MapViewScreen/index.tsx
- components/ProjectItem/styles.ts
- components/ProjectsListingModal/index.tsx
- components/ProjectsListingModal/styles.ts
- components/SearchBar/styles.ts
- components/SortBy/index.tsx
- package.json
- pnpm-lock.yaml
- types/schema.d.ts
- Functions include: sort A-Z, sort Z-A, sort size ascending, sort size descending, sort COD ascending, sort COD descending
- Created a separate SortBy component (takes in projects, category, setSortedProjects state, and toggleSortBy)
- Fixed bug involving the listing modal not displaying correctly when using the search bar, or the sorting resetting
- Merged with work from previous sprints (no projects found)
- Made it so that the sort by closes when the user clicks any sorting option
[//]: # "[Required] For frontend tasks: add screenshots of the layout and …
> Sort By Component + Search bar fixes

- api/supabase/queries/query.ts
- app/layout.tsx
- app/page.tsx
- components/ProjectItem/index.tsx
- components/ProjectModal/index.tsx
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user …
> [bug] fixed image lagging

- components/ProjectSizeHistogram/index.tsx
- components/ProjectSizeSlider/index.tsx
- fixed bug where displayed min and max values in project size dropdown were not being used to filter
[//]: # "/[Required] Describe the order in which to review files and what to expect when testing locally. Is there anything …
> [bug] fixed project size bug

- components/FilterTags/index.tsx
- components/FilterTags/styles.ts
- components/MapViewScreen/index.tsx
- components/ProjectSizeDropdown/index.tsx
- components/ProjectsListingModal/index.tsx
- components/ProjectsListingModal/styles.ts
- context/FilterContext.tsx
- styles/texts.ts
- `FilterTags` component for the applied filter tag
- used react context to pass projectSize filter variables from `MapViewScreen` to `FilterTags` component
- i wrap all of `MapViewScreen` child components with `FilterProvider` so that all the child components (ProjectSizeDropdown, FilterTags, etc) can have access to the variables defined in `FilterContext`
- `projectSizeFilterTagHandler` in `FilterContext` uses the same logic as `filterChangeHandlers` in `FilterBar`
[//]: # "[Required] For frontend tasks: add screenshots of the layout and expected behavior (GIFs …
> [feat] Applied Filters
